# This file was generated by GoReleaser. DO NOT EDIT.
cask "reevit" do
  version "0.6.2"

  on_macos do
    on_intel do
      sha256 "a80bb86dc99f2031bd5fd37f6a4e63f4910c20ab2e09a25023531b437999881a"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1edc6e3f17c9d64407114f20081628e6eff538a81249bdb7a66059f2d36615c"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb71c3b543bf6f3aafd61cfb37fc456946c7e0a4437c88fb449e44809bbe4a1b"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce736b7202a950568f19cd7640e2d9581af251ba639ad14d3d6fc2d49e356776"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "reevit"
  desc "Set up Reevit, generate checkout and webhook integrations, and test payments locally"
  homepage "https://github.com/Reevit-Platform/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reevit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reevit"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Get started inside your application:

      cd your-project
      reevit init

    Documentation:
      https://github.com/Reevit-Platform/cli#readme
  EOS
end
