# This file was generated by GoReleaser. DO NOT EDIT.
cask "reevit" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "8c3e005e3a21d5587095af8ae92aaf75a75bf6336c00cb21a940ae17cfe52250"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3100483a671b1208ea9d307be9c51042bbea98855aa877498b583fc8821a41e1"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b61b58f2711ee19ff2558e44ba97fc9107274135e5d4439a124c1c48266ef694"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "320ceeb0ac6e13b15c8866bb1ae7a76ab473fa47f688a929c9d3153a8c44e367"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "reevit"
  desc "Reevit CLI — test payments, drive the sandbox simulator, forward events locally"
  homepage "https://github.com/Reevit-Platform/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reevit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reevit"]
    end
  end

  # No zap stanza required

end
