# This file was generated by GoReleaser. DO NOT EDIT.
cask "reevit" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "d9cfc37d5be88fa074c09de117489019c7b1f7efe55e51d307588d8bbd81ffbb"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "047fb970324e79c593391dd1d90afef826c61ceec9c23ea7dc722de94b771215"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10678ab79770ca509146b8c92102314484c7e8410f6f3d639a9fd716f5e34c7a"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce768da99bd87a6b82076e33440ab6b0a0a88f92df1cdadae3f64610dbefd07d"
      url "https://github.com/Reevit-Platform/cli/releases/download/v#{version}/reevit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "reevit"
  desc "Reevit CLI — test payments, drive the sandbox simulator, forward events locally"
  homepage "https://github.com/Reevit-Platform/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reevit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reevit"]
    end
  end

  # No zap stanza required

end
